In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import math

In [2]:
y = [892, 809, 823, 798, 671, 644, 883, 903, 677]

In [11]:
def allanoadev(y):
    M = len(y)
    m = np.array([1,2])
    allanvar = []
    for k in range(len(m)):
        outersum = []
        j = 0
        while j < M-2*m[k]+1:
            i = j
            innersum = []
            while i <= j+m[k]-1:
                innersum.append(y[i+m[k]]-y[i])
                i += 1
            outersum.append(0.5*(np.sum(innersum)/m[k])**2)
            j += 1
    
        # Calculate allan variance
        allanvar.append(np.sum(outersum)/(M-2*m[k]+1))
        

    return np.sqrt(allanvar)
    

In [12]:
allanoadev(y)

array([91.22944974, 85.95286984])

In [21]:
def allanmdev(y):
    M = len(y)
    m = np.array([1,2])
    allanvar = []
    for k in range(len(m)):
        outersum = []
        j = 0
        while j < M-3*m[k]+2:
            i = j
            middlesum = []
            while i <= j+m[k]-1:
                n = i
                innersum = []
                while n <= i+m[k]-1:
                    innersum.append(y[n+m[k]]-y[n])
                    n += 1
                middlesum.append(np.sum(innersum))
                i += 1
            outersum.append(np.sum(middlesum)**2)
            j += 1 
    
        # Calculate allan variance
        allanvar.append(np.sum(outersum)/((M-3*m[k]+2)*2*m[k]**4))
        

    return np.sqrt(allanvar)
    

In [22]:
allanmdev(y)

array([91.22944974, 74.78849343])

In [35]:
def haddev(y):
    M = len(y)
    m = np.array([1,2])
    havar = []
    for k in range(len(m)):
        hsum = []
        i = 0
        while i < M-2:
            hsum.append((y[i+2]-2*y[i+1]+y[i])**2)
            i += 1
    
        # Calculate allan variance
        havar.append(np.sum(hsum)/(6*(M-2)))
        

    return np.sqrt(havar)
    

In [36]:
haddev(y)

array([70.80607319, 70.80607319])

In [92]:
def ohdev(y):
    M = len(y)
    m = np.array([1,2])
    havar = []
    for k in range(len(m)):
        outersum = []
        j = 0
        while j < M-3*m[k]+1:
            i = j
            innersum = []
            while i <= j+m[k]-1:
                innersum.append(y[i+2*m[k]]-2*y[i+m[k]]+y[i])
                i += 1
            outersum.append((np.sum(innersum)/m[k])**2)
            j += 1
    
        # Calculate allan variance
        havar.append(np.sum(outersum)/(6*(M-3*m[k]+1)))

    return np.sqrt(havar)
    

In [93]:
ohdev(y)

array([70.80607319, 85.61487166])