In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import math

In [5]:
y = [892, 809, 823, 798, 671, 644, 883, 903, 677]

In [3]:
def allanoadev_opt(y,rate):
        
    # === Parameters ===
    
    N = len(y)
    # m array where 3 < m < N/3 
    m = np.arange(3,1+round(N//3),1)
    # Take tau0 as 1/rate
    tau0 = 1/rate
    # steps
    step = 1
    
    # Empty variance array
    allanvar = []
    # Empty tau values array 
    tau = []

    # Iterate over values of m
    for k in range(len(m)): 
        kernels = np.ones(m[k])/m[k]
        ybar = np.convolve(y,kernels,'valid')

        # M is the number of times we can move the averaging window from the beginning to the end
        M = len(ybar)

        # Calculate allan var 
        outersum = []
        for j in np.arange(0,M-2*m[k]+1,step):
            innersum = []
            for i in np.arange(j,j+m[k]-1,step):
                innersum.append(ybar[i+m[k]]-ybar[i])
            outersum.append(0.5*(np.sum(innersum)/m[k])**2)

        # Calculate allan variance
        allanvar.append(np.sum(outersum)/(M-2*m[k]+1))
        
        # Calculate tau
        tau.append(tau0*m[k])

    # Calculate allan std dev
    allanstd = np.sqrt(allanvar)
        
    return tau, allanstd


In [4]:
tau, allanstd = allanoadev_opt(y,1)

In [5]:
allanstd

array([36.10192191])

In [8]:
N = len(y)
N

9

In [9]:
m = np.array([1])

In [10]:
tau0 = 1

In [15]:
# Empty variance array
allanvar = []
# Empty tau values array 
tau = []
    
for k in range(len(m)): 
#     kernels = np.ones(m[k])/m[k]
#     ybar = np.convolve(y,kernels,'valid')

    left = 0
    right = m[k]
    ybar = []
    while right <= len(y):
        ybar.append(np.mean(y[left:right]))
        
        left += 1
        right += 1

    # M is the number of times we can move the averaging window from the beginning to the end
    M = len(ybar)

    # Calculate allan var 
    outersum = []
    for j in np.arange(0,M-2*m[k]+1,1):
        innersum = []
        for i in np.arange(j,j+m[k]-1,1):
            innersum.append(ybar[i+m[k]]-ybar[i])
        outersum.append(0.5*(np.sum(innersum)/m[k])**2)
        
    outersum = []
    j = 0
    while j < M-2*m[k]+1:
        i = j
        ysum = []
        while i <= j+m[k]-1:
            ysum.append(ybar[i+m[k]]-ybar[i])
            i += 1
        outersum.append(0.5*(np.sum(ysum)/m[k])**2)
        j += 1

    # Calculate allan variance
    allanvar.append(np.sum(outersum)/(M-2*m[k]+1))
        
    # Calculate tau
    tau.append(tau0*m[k])

In [ ]:
    outersum = []
    j = 0
    while j < M-2*m[k]+1:
        i = j
        ysum = []
        while i <= j+m[k]-1:
            ysum.append(ybar[i+m[k]]-ybar[i])
            i += 1
        outersum.append(0.5*(np.sum(ysum)/m[k])**2)
        j += 1


In [16]:
np.sqrt(allanvar)

array([0.])

In [14]:
def allan(y,t):
    #calculate some parameters
#     n = np.arange(3,1+round(len(y)//3),1)
    n=np.array([1])
    t = np.array([1])
    step = 1
    tau0 = np.mean(np.diff(t))

    allanvar = []
    tau = []
    for jj in range(len(n)):
        print(jj)
        #sliding windows
        left = 0
        right = n[jj]
        ytemp = []
        while right <= len(y):
            ytemp.append(np.mean(y[left:right]))
        
            left = left + step
            right = right + step
        M = len(ytemp)
        
        #calculate Allan variance
        ysum2 = []
        i = 0
        while i < M-2*n[jj]+1:
            j = i
            ysum = []
            while j <= i+n[jj]-1:
                ysum.append(ytemp[j+n[jj]]-ytemp[j])
                j = j+step
            ysum2.append(0.5*(np.sum(ysum)/n[jj])**2)
            i = i+step
        allanvar.append(np.sum(ysum2)/(M-2*n[jj]+1))
        tau.append(tau0*n[jj])

    allanstd = np.sqrt(allanvar)
    
    return tau,allanvar,allanstd

In [15]:
allan(y,1)[2]

0


/home/anto/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3441: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/anto/anaconda3/lib/python3.7/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


array([91.22944974])

In [23]:
def allanoadev(y):
        
    # === Parameters ===
    
    # Length of observation
    N = len(y)
        
    # m array where 3 < m < N/3 
#     m = np.arange(3,1+round(N//3),1)
    m = np.array([1])
    # Take tau0 as 1/rate
#     tau0 =  np.mean(np.diff(dates))
    tau0 = 1
    # steps
    step = 1
    
    # Empty variance array
    allanvar = []
    # Empty tau values array 
    tau = []
    
    # Create weights 
#     weights_std = []
#     for val in error:
#         if val != 0:
#             weights_std.append(1/(val**2))
#         elif val == 0:
#             weights_std.append(0)

    # Iterate over values of m
    for k in range(len(m)): 
        print('Current value of m: ', m[k])
        # Sliding windows 
        left = 0 
        right = m[k]
        ybar = []
        D = 0
        data_sum = 0
        
        # Check for missing windows 
        while right <= N:
            data_values = y[left:right]
            data_sum = np.sum(data_values)
    
            if data_sum == 0:
                D +=1
            else:
                avg = np.average(data_values)
                ybar.append(avg)
            left += step 
            right += step    
            

        M_D = len(ybar)

        # Calculate allan var 
        outersum = []
        j = 0
        while j < M_D-2*m[k]+1:
            i = j
            ysum = []
            while i <= j+m[k]-1:
                ysum.append(ybar[i+m[k]]-ybar[i])
                i += 1
            outersum.append(0.5*(np.sum(ysum)/m[k])**2)
            j += 1


        # Calculate allan variance
        allanvar.append(np.sum(outersum)/(M_D-2*m[k]+1))
        
        # Calculate tau
        tau.append(tau0*m[k])

    # Calculate allan std dev
    allanstd = np.sqrt(allanvar)
        
    return tau, allanstd


In [24]:
allanoadev(y)

Current value of m:  1


([1], array([91.22944974]))

In [29]:
def allanoadev_new(y,t,error):
        
    # === Parameters ===
    
    # Length of observation
    N = len(y)
        
    # m array where 3 < m < N/3 
#     m = np.arange(3,1+round(N//3),1)
    m = np.array([1])
    # initial sampling time
    if t is None:
        tau0 = 1
    else:
        tau0 =  np.mean(np.diff(t))
    # steps
    step = tau0
    
    # Empty variance array
    allanvar = []
    # Empty tau values array 
    tau = []

    # Iterate over values of m
    for k in range(len(m)): 
        # Sliding windows 
        if t is None:
            left = 0
            right = m[k]
            maxdata = N
        else:
            left = min(t)
            right = min(t) + m[k]*tau0
            maxdata = N

        # Array for averages
        ybar = []

        # Array for amount of data points
        Nrray = []

        # Define no of windows with <= 2 data points
        nconstraint = 2
                
        # Check for missing windows 
        while right <= maxdata:
            if t is None:
                data_values = y[left:right]
            else:
                data_values = y[(t>=left) & (t<=right)]
                
            Ndata = len(data_values)
            Nrray.append(Ndata)

            if Ndata == 0:
                ybar.append(np.nan)
            else:
                if error is None and t is None: 
                    avg = np.average(data_values)
                    ybar.append(avg)
                else:
                    weights_std = 1/error[(t>=left) & (t<=right)]**2
                    avg = np.average(data_values, weights=weights_std)
                    ybar.append(avg)
            left += step 
            right += step    

        # Define empty windows 
        Nrray = np.array(Nrray)
        ybar = np.array(ybar)
        
        D = len(ybar[Nrray<=nconstraint])
        M = len(ybar)
        print(k,len(m),M,D)

        # Discard windows with too few data points
        ybar = ybar[Nrray>nconstraint]

        # Calculate allan var 
        outersum = []
        j = 0
        while j < M-2*m[k]+1-D:
            i = j
            innersum = []
            while i <= j+m[k]-1:
                innersum.append(ybar[i+m[k]]-ybar[i])
                i += 1
            outersum.append(0.5*(np.sum(innersum)/m[k])**2)
            j += 1


        # Calculate allan variance
        allanvar.append(np.sum(outersum)/(M-2*m[k]+1-D))
        
        # Calculate tau
        tau.append(tau0*m[k])

    # Calculate allan std dev
    allanstd = np.sqrt(allanvar)
        
    return tau, allanstd


In [30]:
allanoadev_new(y,None,None)

0 1 9 9


([1], array([-0.]))

In [24]:
allanoadev_new(y,taus,None)

Current value of m:  3


TypeError: only integer scalar arrays can be converted to a scalar index